# No Terminales
S = 0
Sp = 1
O = 2
Op = 3
T = 4
Tp = 5
Ov = 6
V = 7
Vp = 8
N = 9
Np = 10
Val = 11
Dt = 12
I = 13
Ip = 14
M = 15
C = 16
Cp = 17
B = 18
F = 19
Fp = 20
G = 21
P = 22
Pp = 23
L = 24
Lp = 25
R = 26
Sc = 27
Pr = 28
W = 29
A = 30
D = 31
E = 32

# Gramaticas
S_table = [
    [S, "EOF", None],
    [S, "INCLUDE", ["INCLUDE", "LESS_THAN", "IDENTIFIER", "GREATER_THAN", Sp]],
    [S, "LEFT_PARENTHESIS", None],
    [S, "RIGHT_PARENTHESIS", None],
    [S, "LEFT_BLOCK", None],
    [S, "RIGHT_BLOCK", None],
    [S, "INSTRUCTION_END", None],
    [S, "COMMA", None],
    [S, "EQUAL", None],
    [S, "LESS_THAN", None],
    [S, "GREATER_THAN", None],
    [S, "PLUS", None],
    [S, "MINUS", None],
    [S, "TIMES", None],
    [S, "DIVIDE", None],
    [S, "IDENTIFIER", None],
    [S, "CHAR_DEFINITION", None],
    [S, "NUMBER", None],
    [S, "STRING_DEFINITION", None],
    [S, "IF", None],
    [S, "ELSE", None],
    [S, "COMMENT", ["COMMENT", S]],
    [S, "STRING", [F, Sp]],
    [S, "CHAR", [F, Sp]],
    [S, "INT", [F, Sp]],
    [S, "FLOAT", [F, Sp]],
    [S, "PRINTF", None],
    [S, "SCANF", None],
    [S, "WHILE", None],
    [S, "RETURN", None],
]

Sp_table = [
    [Sp, "EOF", ["VACIA"]],
    [Sp, "INCLUDE", None],
    [Sp, "LEFT_PARENTHESIS", None],
    [Sp, "RIGHT_PARENTHESIS", None],
    [Sp, "LEFT_BLOCK", None],
    [Sp, "RIGHT_BLOCK", None],
    [Sp, "INSTRUCTION_END", None],
    [Sp, "COMMA", None],
    [Sp, "EQUAL", None],
    [Sp, "LESS_THAN", None],
    [Sp, "GREATER_THAN", None],
    [Sp, "PLUS", None],
    [Sp, "MINUS", None],
    [Sp, "TIMES", None],
    [Sp, "DIVIDE", None],
    [Sp, "IDENTIFIER", None],
    [Sp, "CHAR_DEFINITION", None],
    [Sp, "NUMBER", None],
    [Sp, "STRING_DEFINITION", None],
    [Sp, "IF", None],
    [Sp, "ELSE", None],
    [Sp, "COMMENT", ["COMMENT", S]],
    [Sp, "STRING", [F, Sp]],
    [Sp, "CHAR", [F, Sp]],
    [Sp, "INT", [F, Sp]],
    [Sp, "FLOAT", [F, Sp]],
    [Sp, "PRINTF", None],
    [Sp, "SCANF", None],
    [Sp, "WHILE", None],
    [Sp, "RETURN", None],
]

O_table = [
    [O, "EOF", None],
    [O, "INCLUDE", None],
    [O, "LEFT_PARENTHESIS", [T, Op]],
    [O, "RIGHT_PARENTHESIS", None],
    [O, "LEFT_BLOCK", None],
    [O, "RIGHT_BLOCK", None],
    [O, "INSTRUCTION_END", None],
    [O, "COMMA", None],
    [O, "EQUAL", None],
    [O, "LESS_THAN", None],
    [O, "GREATER_THAN", None],
    [O, "PLUS", None],
    [O, "MINUS", None],
    [O, "TIMES", None],
    [O, "DIVIDE", None],
    [O, "IDENTIFIER", [T, Op]],
    [O, "CHAR_DEFINITION", None],
    [O, "NUMBER", [T, Op]],
    [O, "STRING_DEFINITION", None],
    [O, "IF", None],
    [O, "ELSE", None],
    [O, "COMMENT", None],
    [O, "STRING", None],
    [O, "CHAR", None],
    [O, "INT", None],
    [O, "FLOAT", None],
    [O, "PRINTF", None],
    [O, "SCANF", None],
    [O, "WHILE", None],
    [O, "RETURN", None],
]

Op_table = [
    [Op, "EOF", None],
    [Op, "INCLUDE", None],
    [Op, "LEFT_PARENTHESIS", None],
    [Op, "RIGHT_PARENTHESIS", ["VACIA"]],
    [Op, "LEFT_BLOCK", None],
    [Op, "RIGHT_BLOCK", None],
    [Op, "INSTRUCTION_END", ["VACIA"]],
    [Op, "COMMA", ["VACIA"]],
    [Op, "EQUAL", ["VACIA"]],
    [Op, "LESS_THAN", ["VACIA"]],
    [Op, "GREATER_THAN", ["VACIA"]],
    [Op, "PLUS", ["PLUS", T, Op]],
    [Op, "MINUS", ["MINUS", T, Op]],
    [Op, "TIMES", None],
    [Op, "DIVIDE", None],
    [Op, "IDENTIFIER", None],
    [Op, "CHAR_DEFINITION", None],
    [Op, "NUMBER", None],
    [Op, "STRING_DEFINITION", None],
    [Op, "IF", None],
    [Op, "ELSE", None],
    [Op, "COMMENT", None],
    [Op, "STRING", None],
    [Op, "CHAR", None],
    [Op, "INT", None],
    [Op, "FLOAT", None],
    [Op, "PRINTF", None],
    [Op, "SCANF", None],
    [Op, "WHILE", None],
    [Op, "RETURN", None],
]

T_table = [
    [T, "EOF", None],
    [T, "INCLUDE", None],
    [T, "LEFT_PARENTHESIS", [Ov, Tp]],
    [T, "RIGHT_PARENTHESIS", None],
    [T, "LEFT_BLOCK", None],
    [T, "RIGHT_BLOCK", None],
    [T, "INSTRUCTION_END", None],
    [T, "COMMA", None],
    [T, "EQUAL", None],
    [T, "LESS_THAN", None],
    [T, "GREATER_THAN", None],
    [T, "PLUS", None],
    [T, "MINUS", None],
    [T, "TIMES", None],
    [T, "DIVIDE", None],
    [T, "IDENTIFIER", [Ov, Tp]],
    [T, "CHAR_DEFINITION", None],
    [T, "NUMBER", [Ov, Tp]],
    [T, "STRING_DEFINITION", None],
    [T, "IF", None],
    [T, "ELSE", None],
    [T, "COMMENT", None],
    [T, "STRING", None],
    [T, "CHAR", None],
    [T, "INT", None],
    [T, "FLOAT", None],
    [T, "PRINTF", None],
    [T, "SCANF", None],
    [T, "WHILE", None],
    [T, "RETURN", None],
]

Tp_table = [
    [Tp, "EOF", None],
    [Tp, "INCLUDE", None],
    [Tp, "LEFT_PARENTHESIS", None],
    [Tp, "RIGHT_PARENTHESIS", ["VACIA"]],
    [Tp, "LEFT_BLOCK", None],
    [Tp, "RIGHT_BLOCK", None],
    [Tp, "INSTRUCTION_END", ["VACIA"]],
    [Tp, "COMMA", ["VACIA"]],
    [Tp, "EQUAL", ["VACIA"]],
    [Tp, "LESS_THAN", ["VACIA"]],
    [Tp, "GREATER_THAN", ["VACIA"]],
    [Tp, "PLUS", ["VACIA"]],
    [Tp, "MINUS", ["VACIA"]],
    [Tp, "TIMES", ["TIMES", Ov, Tp]],
    [Tp, "DIVIDE", ["DIVIDE", Ov, Tp]],
    [Tp, "IDENTIFIER", None],
    [Tp, "CHAR_DEFINITION", None],
    [Tp, "NUMBER", None],
    [Tp, "STRING_DEFINITION", None],
    [Tp, "IF", None],
    [Tp, "ELSE", None],
    [Tp, "COMMENT", None],
    [Tp, "STRING", None],
    [Tp, "CHAR", None],
    [Tp, "INT", None],
    [Tp, "FLOAT", None],
    [Tp, "PRINTF", None],
    [Tp, "SCANF", None],
    [Tp, "WHILE", None],
    [Tp, "RETURN", None],
]

Ov_table = [
    [Ov, "EOF", None],
    [Ov, "INCLUDE", None],
    [Ov, "LEFT_PARENTHESIS", ["LEFT_PARENTHESIS", O, "RIGHT_PARENTHESIS"]],
    [Ov, "RIGHT_PARENTHESIS", None],
    [Ov, "LEFT_BLOCK", None],
    [Ov, "RIGHT_BLOCK", None],
    [Ov, "INSTRUCTION_END", None],
    [Ov, "COMMA", None],
    [Ov, "EQUAL", None],
    [Ov, "LESS_THAN", None],
    [Ov, "GREATER_THAN", None],
    [Ov, "PLUS", None],
    [Ov, "MINUS", None],
    [Ov, "TIMES", None],
    [Ov, "DIVIDE", None],
    [Ov, "IDENTIFIER", ["IDENTIFIER"]],
    [Ov, "CHAR_DEFINITION", None],
    [Ov, "NUMBER", ["NUMBER"]],
    [Ov, "STRING_DEFINITION", None],
    [Ov, "IF", None],
    [Ov, "ELSE", None],
    [Ov, "COMMENT", None],
    [Ov, "STRING", None],
    [Ov, "CHAR", None],
    [Ov, "INT", None],
    [Ov, "FLOAT", None],
    [Ov, "PRINTF", None],
    [Ov, "SCANF", None],
    [Ov, "WHILE", None],
    [Ov, "RETURN", None],
]

V_table = [
    [V, "EOF", None],
    [V, "INCLUDE", None],
    [V, "LEFT_PARENTHESIS", None],
    [V, "RIGHT_PARENTHESIS", None],
    [V, "LEFT_BLOCK", None],
    [V, "RIGHT_BLOCK", None],
    [V, "INSTRUCTION_END", None],
    [V, "COMMA", None],
    [V, "EQUAL", None],
    [V, "LESS_THAN", None],
    [V, "GREATER_THAN", None],
    [V, "PLUS", None],
    [V, "MINUS", None],
    [V, "TIMES", None],
    [V, "DIVIDE", None],
    [V, "IDENTIFIER", None],
    [V, "CHAR_DEFINITION", None],
    [V, "NUMBER", None],
    [V, "STRING_DEFINITION", None],
    [V, "IF", None],
    [V, "ELSE", None],
    [V, "COMMENT", None],
    [V, "STRING", [Dt, Vp]],
    [V, "CHAR", [Dt, Vp]],
    [V, "INT", [Dt, Vp]],
    [V, "FLOAT", [Dt, Vp]],
    [V, "PRINTF", None],
    [V, "SCANF", None],
    [V, "WHILE", None],
    [V, "RETURN", None],
]

Vp_table = [
    [Vp, "EOF", None],
    [Vp, "INCLUDE", None],
    [Vp, "LEFT_PARENTHESIS", None],
    [Vp, "RIGHT_PARENTHESIS", None],
    [Vp, "LEFT_BLOCK", None],
    [Vp, "RIGHT_BLOCK", None],
    [Vp, "INSTRUCTION_END", None],
    [Vp, "COMMA", None],
    [Vp, "EQUAL", None],
    [Vp, "LESS_THAN", None],
    [Vp, "GREATER_THAN", None],
    [Vp, "PLUS", None],
    [Vp, "MINUS", None],
    [Vp, "TIMES", None],
    [Vp, "DIVIDE", None],
    [Vp, "IDENTIFIER", ["IDENTIFIER", N]],
    [Vp, "CHAR_DEFINITION", None],
    [Vp, "NUMBER", None],
    [Vp, "STRING_DEFINITION", None],
    [Vp, "IF", None],
    [Vp, "ELSE", None],
    [Vp, "COMMENT", None],
    [Vp, "STRING", None],
    [Vp, "CHAR", None],
    [Vp, "INT", None],
    [Vp, "FLOAT", None],
    [Vp, "PRINTF", None],
    [Vp, "SCANF", None],
    [Vp, "WHILE", None],
    [Vp, "RETURN", None],
]

N_table = [
    [N, "EOF", None],
    [N, "INCLUDE", None],
    [N, "LEFT_PARENTHESIS", None],
    [N, "RIGHT_PARENTHESIS", None],
    [N, "LEFT_BLOCK", None],
    [N, "RIGHT_BLOCK", None],
    [N, "INSTRUCTION_END", [Np]],
    [N, "COMMA", [Np]],
    [N, "EQUAL", ["EQUAL", Val, Np]],
    [N, "LESS_THAN", None],
    [N, "GREATER_THAN", None],
    [N, "PLUS", None],
    [N, "MINUS", None],
    [N, "TIMES", None],
    [N, "DIVIDE", None],
    [N, "IDENTIFIER", None],
    [N, "CHAR_DEFINITION", None],
    [N, "NUMBER", None],
    [N, "STRING_DEFINITION", None],
    [N, "IF", None],
    [N, "ELSE", None],
    [N, "COMMENT", None],
    [N, "STRING", None],
    [N, "CHAR", None],
    [N, "INT", None],
    [N, "FLOAT", None],
    [N, "PRINTF", None],
    [N, "SCANF", None],
    [N, "WHILE", None],
    [N, "RETURN", None],
]

Np_table = [
    [Np, "EOF", None],
    [Np, "INCLUDE", None],
    [Np, "LEFT_PARENTHESIS", None],
    [Np, "RIGHT_PARENTHESIS", None],
    [Np, "LEFT_BLOCK", None],
    [Np, "RIGHT_BLOCK", None],
    [Np, "INSTRUCTION_END", ["INSTRUCTION_END"]],
    [Np, "COMMA", ["COMMA", Vp]],
    [Np, "EQUAL", None],
    [Np, "LESS_THAN", None],
    [Np, "GREATER_THAN", None],
    [Np, "PLUS", None],
    [Np, "MINUS", None],
    [Np, "TIMES", None],
    [Np, "DIVIDE", None],
    [Np, "IDENTIFIER", None],
    [Np, "CHAR_DEFINITION", None],
    [Np, "NUMBER", None],
    [Np, "STRING_DEFINITION", None],
    [Np, "IF", None],
    [Np, "ELSE", None],
    [Np, "COMMENT", None],
    [Np, "STRING", None],
    [Np, "CHAR", None],
    [Np, "INT", None],
    [Np, "FLOAT", None],
    [Np, "PRINTF", None],
    [Np, "SCANF", None],
    [Np, "WHILE", None],
    [Np, "RETURN", None],
]

Val_table = [
    [Val, "EOF", None],
    [Val, "INCLUDE", None],
    [Val, "LEFT_PARENTHESIS", [O]],
    [Val, "RIGHT_PARENTHESIS", None],
    [Val, "LEFT_BLOCK", None],
    [Val, "RIGHT_BLOCK", None],
    [Val, "INSTRUCTION_END", None],
    [Val, "COMMA", None],
    [Val, "EQUAL", None],
    [Val, "LESS_THAN", None],
    [Val, "GREATER_THAN", None],
    [Val, "PLUS", None],
    [Val, "MINUS", None],
    [Val, "TIMES", None],
    [Val, "DIVIDE", None],
    [Val, "IDENTIFIER", [O]],
    [Val, "CHAR_DEFINITION", ["CHAR_DEFINITION"]],
    [Val, "NUMBER", [O]],
    [Val, "STRING_DEFINITION", ["STRING_DEFINITION"]],
    [Val, "IF", None],
    [Val, "ELSE", None],
    [Val, "COMMENT", None],
    [Val, "STRING", None],
    [Val, "CHAR", None],
    [Val, "INT", None],
    [Val, "FLOAT", None],
    [Val, "PRINTF", None],
    [Val, "SCANF", None],
    [Val, "WHILE", None],
    [Val, "RETURN", None],
]

Dt_table = [
    [Dt, "EOF", None],
    [Dt, "INCLUDE", None],
    [Dt, "LEFT_PARENTHESIS", None],
    [Dt, "RIGHT_PARENTHESIS", None],
    [Dt, "LEFT_BLOCK", None],
    [Dt, "RIGHT_BLOCK", None],
    [Dt, "INSTRUCTION_END", None],
    [Dt, "COMMA", None],
    [Dt, "EQUAL", None],
    [Dt, "LESS_THAN", None],
    [Dt, "GREATER_THAN", None],
    [Dt, "PLUS", None],
    [Dt, "MINUS", None],
    [Dt, "TIMES", None],
    [Dt, "DIVIDE", None],
    [Dt, "IDENTIFIER", None],
    [Dt, "CHAR_DEFINITION", None],
    [Dt, "NUMBER", None],
    [Dt, "STRING_DEFINITION", None],
    [Dt, "IF", None],
    [Dt, "ELSE", None],
    [Dt, "COMMENT", None],
    [Dt, "STRING", ["STRING"]],
    [Dt, "CHAR", ["CHAR"]],
    [Dt, "INT", ["INT"]],
    [Dt, "FLOAT", ["FLOAT"]],
    [Dt, "PRINTF", None],
    [Dt, "SCANF", None],
    [Dt, "WHILE", None],
    [Dt, "RETURN", None],
]

I_table = [
    [I, "EOF", None],
    [I, "INCLUDE", None],
    [I, "LEFT_PARENTHESIS", None],
    [I, "RIGHT_PARENTHESIS", None],
    [I, "LEFT_BLOCK", None],
    [I, "RIGHT_BLOCK", None],
    [I, "INSTRUCTION_END", None],
    [I, "COMMA", None],
    [I, "EQUAL", None],
    [I, "LESS_THAN", None],
    [I, "GREATER_THAN", None],
    [I, "PLUS", None],
    [I, "MINUS", None],
    [I, "TIMES", None],
    [I, "DIVIDE", None],
    [I, "IDENTIFIER", None],
    [I, "CHAR_DEFINITION", None],
    [I, "NUMBER", None],
    [I, "STRING_DEFINITION", None],
    [
        I,
        "IF",
        [
            "IF",
            "LEFT_PARENTHESIS",
            C,
            "RIGHT_PARENTHESIS",
            "LEFT_BLOCK",
            L,
            "RIGHT_BLOCK",
            Ip,
        ],
    ],
    [I, "ELSE", None],
    [I, "COMMENT", None],
    [I, "STRING", None],
    [I, "CHAR", None],
    [I, "INT", None],
    [I, "FLOAT", None],
    [I, "PRINTF", None],
    [I, "SCANF", None],
    [I, "WHILE", None],
    [I, "RETURN", None],
]

Ip_table = [
    [Ip, "EOF", None],
    [Ip, "INCLUDE", None],
    [Ip, "LEFT_PARENTHESIS", None],
    [Ip, "RIGHT_PARENTHESIS", None],
    [Ip, "LEFT_BLOCK", None],
    [Ip, "RIGHT_BLOCK", None],
    [Ip, "INSTRUCTION_END", ["INSTRUCTION_END"]],
    [Ip, "COMMA", None],
    [Ip, "EQUAL", None],
    [Ip, "LESS_THAN", None],
    [Ip, "GREATER_THAN", None],
    [Ip, "PLUS", None],
    [Ip, "MINUS", None],
    [Ip, "TIMES", None],
    [Ip, "DIVIDE", None],
    [Ip, "IDENTIFIER", None],
    [Ip, "CHAR_DEFINITION", None],
    [Ip, "NUMBER", None],
    [Ip, "STRING_DEFINITION", None],
    [Ip, "IF", None],
    [Ip, "ELSE", ["ELSE", M]],
    [Ip, "COMMENT", None],
    [Ip, "STRING", None],
    [Ip, "CHAR", None],
    [Ip, "INT", None],
    [Ip, "FLOAT", None],
    [Ip, "PRINTF", None],
    [Ip, "SCANF", None],
    [Ip, "WHILE", None],
    [Ip, "RETURN", None],
]

M_table = [
    [M, "EOF", None],
    [M, "INCLUDE", None],
    [M, "LEFT_PARENTHESIS", None],
    [M, "RIGHT_PARENTHESIS", None],
    [M, "LEFT_BLOCK", ["LEFT_BLOCK", L, "RIGHT_BLOCK"]],
    [M, "RIGHT_BLOCK", None],
    [M, "INSTRUCTION_END", None],
    [M, "COMMA", None],
    [M, "EQUAL", None],
    [M, "LESS_THAN", None],
    [M, "GREATER_THAN", None],
    [M, "PLUS", None],
    [M, "MINUS", None],
    [M, "TIMES", None],
    [M, "DIVIDE", None],
    [M, "IDENTIFIER", None],
    [M, "CHAR_DEFINITION", None],
    [M, "NUMBER", None],
    [M, "STRING_DEFINITION", None],
    [M, "IF", [I]],
    [M, "ELSE", None],
    [M, "COMMENT", None],
    [M, "STRING", None],
    [M, "CHAR", None],
    [M, "INT", None],
    [M, "FLOAT", None],
    [M, "PRINTF", None],
    [M, "SCANF", None],
    [M, "WHILE", None],
    [M, "RETURN", None],
]

C_table = [
    [C, "EOF", None],
    [C, "INCLUDE", None],
    [C, "LEFT_PARENTHESIS", None],
    [C, "RIGHT_PARENTHESIS", None],
    [C, "LEFT_BLOCK", None],
    [C, "RIGHT_BLOCK", None],
    [C, "INSTRUCTION_END", None],
    [C, "COMMA", None],
    [C, "EQUAL", None],
    [C, "LESS_THAN", None],
    [C, "GREATER_THAN", None],
    [C, "PLUS", None],
    [C, "MINUS", None],
    [C, "TIMES", None],
    [C, "DIVIDE", None],
    [C, "IDENTIFIER", [O, Cp]],
    [C, "CHAR_DEFINITION", None],
    [C, "NUMBER", [O, Cp]],
    [C, "STRING_DEFINITION", None],
    [C, "IF", None],
    [C, "ELSE", None],
    [C, "COMMENT", None],
    [C, "STRING", None],
    [C, "CHAR", None],
    [C, "INT", None],
    [C, "FLOAT", None],
    [C, "PRINTF", None],
    [C, "SCANF", None],
    [C, "WHILE", None],
    [C, "RETURN", None],
]

Cp_table = [
    [Cp, "EOF", None],
    [Cp, "INCLUDE", None],
    [Cp, "LEFT_PARENTHESIS", None],
    [Cp, "RIGHT_PARENTHESIS", None],
    [Cp, "LEFT_BLOCK", None],
    [Cp, "RIGHT_BLOCK", None],
    [Cp, "INSTRUCTION_END", None],
    [Cp, "COMMA", None],
    [Cp, "EQUAL", ["EQUAL", B]],
    [Cp, "LESS_THAN", ["LESS_THAN", B]],
    [Cp, "GREATER_THAN", ["GREATER_THAN", B]],
    [Cp, "PLUS", None],
    [Cp, "MINUS", None],
    [Cp, "TIMES", None],
    [Cp, "DIVIDE", None],
    [Cp, "IDENTIFIER", None],
    [Cp, "CHAR_DEFINITION", None],
    [Cp, "NUMBER", None],
    [Cp, "STRING_DEFINITION", None],
    [Cp, "IF", None],
    [Cp, "ELSE", None],
    [Cp, "COMMENT", None],
    [Cp, "STRING", None],
    [Cp, "CHAR", None],
    [Cp, "INT", None],
    [Cp, "FLOAT", None],
    [Cp, "PRINTF", None],
    [Cp, "SCANF", None],
    [Cp, "WHILE", None],
    [Cp, "RETURN", None],
]

B_Table = [
    [B, "EOF", None],
    [B, "INCLUDE", None],
    [B, "LEFT_PARENTHESIS", None],
    [B, "RIGHT_PARENTHESIS", None],
    [B, "LEFT_BLOCK", None],
    [B, "RIGHT_BLOCK", None],
    [B, "INSTRUCTION_END", None],
    [B, "COMMA", None],
    [B, "EQUAL", ["EQUAL", O]],
    [B, "LESS_THAN", None],
    [B, "GREATER_THAN", None],
    [B, "PLUS", None],
    [B, "MINUS", None],
    [B, "TIMES", None],
    [B, "DIVIDE", None],
    [B, "IDENTIFIER", [O]],
    [B, "CHAR_DEFINITION", None],
    [B, "NUMBER", [O]],
    [B, "STRING_DEFINITION", None],
    [B, "IF", None],
    [B, "ELSE", None],
    [B, "COMMENT", None],
    [B, "STRING", None],
    [B, "CHAR", None],
    [B, "INT", None],
    [B, "FLOAT", None],
    [B, "PRINTF", None],
    [B, "SCANF", None],
    [B, "WHILE", None],
    [B, "RETURN", None],
]

F_table = [
    [F, "EOF", None],
    [F, "INCLUDE", None],
    [F, "LEFT_PARENTHESIS", None],
    [F, "RIGHT_PARENTHESIS", None],
    [F, "LEFT_BLOCK", None],
    [F, "RIGHT_BLOCK", None],
    [F, "INSTRUCTION_END", None],
    [F, "COMMA", None],
    [F, "EQUAL", None],
    [F, "LESS_THAN", None],
    [F, "GREATER_THAN", None],
    [F, "PLUS", None],
    [F, "MINUS", None],
    [F, "TIMES", None],
    [F, "DIVIDE", None],
    [F, "IDENTIFIER", None],
    [F, "CHAR_DEFINITION", None],
    [F, "NUMBER", None],
    [F, "STRING_DEFINITION", None],
    [F, "IF", None],
    [F, "ELSE", None],
    [F, "COMMENT", None],
    [F, "STRING", [Dt, "IDENTIFIER", "LEFT_PARENTHESIS", G, "RIGHT_PARENTHESIS", Fp]],
    [F, "CHAR", [Dt, "IDENTIFIER", "LEFT_PARENTHESIS", G, "RIGHT_PARENTHESIS", Fp]],
    [F, "INT", [Dt, "IDENTIFIER", "LEFT_PARENTHESIS", G, "RIGHT_PARENTHESIS", Fp]],
    [F, "FLOAT", [Dt, "IDENTIFIER", "LEFT_PARENTHESIS", G, "RIGHT_PARENTHESIS", Fp]],
    [F, "PRINTF", None],
    [F, "SCANF", None],
    [F, "WHILE", None],
    [F, "RETURN", None],
]

Fp_table = [
    [Fp, "EOF", None],
    [Fp, "INCLUDE", None],
    [Fp, "LEFT_PARENTHESIS", None],
    [Fp, "RIGHT_PARENTHESIS", None],
    [Fp, "LEFT_BLOCK", ["LEFT_BLOCK", L, "RIGHT_BLOCK"]],
    [Fp, "RIGHT_BLOCK", None],
    [Fp, "INSTRUCTION_END", ["INSTRUCTION_END"]],
    [Fp, "COMMA", None],
    [Fp, "EQUAL", None],
    [Fp, "LESS_THAN", None],
    [Fp, "GREATER_THAN", None],
    [Fp, "PLUS", None],
    [Fp, "MINUS", None],
    [Fp, "TIMES", None],
    [Fp, "DIVIDE", None],
    [Fp, "IDENTIFIER", None],
    [Fp, "CHAR_DEFINITION", None],
    [Fp, "NUMBER", None],
    [Fp, "STRING_DEFINITION", None],
    [Fp, "IF", None],
    [Fp, "ELSE", None],
    [Fp, "COMMENT", None],
    [Fp, "STRING", None],
    [Fp, "CHAR", None],
    [Fp, "INT", None],
    [Fp, "FLOAT", None],
    [Fp, "PRINTF", None],
    [Fp, "SCANF", None],
    [Fp, "WHILE", None],
    [Fp, "RETURN", None],
]

G_table = [
    [G, "EOF", None],
    [G, "INCLUDE", None],
    [G, "LEFT_PARENTHESIS", None],
    [G, "RIGHT_PARENTHESIS", ["VACIA"]],
    [G, "LEFT_BLOCK", None],
    [G, "RIGHT_BLOCK", None],
    [G, "INSTRUCTION_END", None],
    [G, "COMMA", None],
    [G, "EQUAL", None],
    [G, "LESS_THAN", None],
    [G, "GREATER_THAN", None],
    [G, "PLUS", None],
    [G, "MINUS", None],
    [G, "TIMES", None],
    [G, "DIVIDE", None],
    [G, "IDENTIFIER", None],
    [G, "CHAR_DEFINITION", None],
    [G, "NUMBER", None],
    [G, "STRING_DEFINITION", None],
    [G, "IF", None],
    [G, "ELSE", None],
    [G, "COMMENT", None],
    [G, "STRING", [P]],
    [G, "CHAR", [P]],
    [G, "INT", [P]],
    [G, "FLOAT", [P]],
    [G, "PRINTF", None],
    [G, "SCANF", None],
    [G, "WHILE", None],
    [G, "RETURN", None],
]

P_table = [
    [P, "EOF", None],
    [P, "INCLUDE", None],
    [P, "LEFT_PARENTHESIS", None],
    [P, "RIGHT_PARENTHESIS", None],
    [P, "LEFT_BLOCK", None],
    [P, "RIGHT_BLOCK", None],
    [P, "INSTRUCTION_END", None],
    [P, "COMMA", None],
    [P, "EQUAL", None],
    [P, "LESS_THAN", None],
    [P, "GREATER_THAN", None],
    [P, "PLUS", None],
    [P, "MINUS", None],
    [P, "TIMES", None],
    [P, "DIVIDE", None],
    [P, "IDENTIFIER", None],
    [P, "CHAR_DEFINITION", None],
    [P, "NUMBER", None],
    [P, "STRING_DEFINITION", None],
    [P, "IF", None],
    [P, "ELSE", None],
    [P, "COMMENT", None],
    [P, "STRING", [Dt, "IDENTIFIER", Pp]],
    [P, "CHAR", [Dt, "IDENTIFIER", Pp]],
    [P, "INT", [Dt, "IDENTIFIER", Pp]],
    [P, "FLOAT", [Dt, "IDENTIFIER", Pp]],
    [P, "PRINTF", None],
    [P, "SCANF", None],
    [P, "WHILE", None],
    [P, "RETURN", None],
]

Pp_table = [
    [Pp, "EOF", None],
    [Pp, "INCLUDE", None],
    [Pp, "LEFT_PARENTHESIS", None],
    [Pp, "RIGHT_PARENTHESIS", ["VACIA"]],
    [Pp, "LEFT_BLOCK", None],
    [Pp, "RIGHT_BLOCK", None],
    [Pp, "INSTRUCTION_END", None],
    [Pp, "COMMA", ["COMMA", P]],
    [Pp, "EQUAL", None],
    [Pp, "LESS_THAN", None],
    [Pp, "GREATER_THAN", None],
    [Pp, "PLUS", None],
    [Pp, "MINUS", None],
    [Pp, "TIMES", None],
    [Pp, "DIVIDE", None],
    [Pp, "IDENTIFIER", None],
    [Pp, "CHAR_DEFINITION", None],
    [Pp, "NUMBER", None],
    [Pp, "STRING_DEFINITION", None],
    [Pp, "IF", None],
    [Pp, "ELSE", None],
    [Pp, "COMMENT", None],
    [Pp, "STRING", None],
    [Pp, "CHAR", None],
    [Pp, "INT", None],
    [Pp, "FLOAT", None],
    [Pp, "PRINTF", None],
    [Pp, "SCANF", None],
    [Pp, "WHILE", None],
    [Pp, "RETURN", None],
]

L_table = [
    [L, "EOF", None],
    [L, "INCLUDE", None],
    [L, "LEFT_PARENTHESIS", None],
    [L, "RIGHT_PARENTHESIS", None],
    [L, "LEFT_BLOCK", None],
    [L, "RIGHT_BLOCK", None],
    [L, "INSTRUCTION_END", None],
    [L, "COMMA", None],
    [L, "EQUAL", None],
    [L, "LESS_THAN", None],
    [L, "GREATER_THAN", None],
    [L, "PLUS", None],
    [L, "MINUS", None],
    [L, "TIMES", None],
    [L, "DIVIDE", None],
    [L, "IDENTIFIER", ["IDENTIFIER", R, Lp]],
    [L, "CHAR_DEFINITION", None],
    [L, "NUMBER", None],
    [L, "STRING_DEFINITION", None],
    [L, "IF", [I, Lp]],
    [L, "ELSE", None],
    [L, "COMMENT", ["COMMENT", Lp]],
    [L, "STRING", [V, Lp]],
    [L, "CHAR", [V, Lp]],
    [L, "INT", [V, Lp]],
    [L, "FLOAT", [V, Lp]],
    [L, "PRINTF", [Pr, Lp]],
    [L, "SCANF", [Sc, Lp]],
    [L, "WHILE", [W, Lp]],
    [L, "RETURN", ["RETURN", Val, "INSTRUCTION_END"]],
]

Lp_table = [
    [Lp, "EOF", None],
    [Lp, "INCLUDE", None],
    [Lp, "LEFT_PARENTHESIS", None],
    [Lp, "RIGHT_PARENTHESIS", None],
    [Lp, "LEFT_BLOCK", None],
    [Lp, "RIGHT_BLOCK", ["VACIA"]],
    [Lp, "INSTRUCTION_END", None],
    [Lp, "COMMA", None],
    [Lp, "EQUAL", None],
    [Lp, "LESS_THAN", None],
    [Lp, "GREATER_THAN", None],
    [Lp, "PLUS", None],
    [Lp, "MINUS", None],
    [Lp, "TIMES", None],
    [Lp, "DIVIDE", None],
    [Lp, "IDENTIFIER", ["IDENTIFIER", R, Lp]],
    [Lp, "CHAR_DEFINITION", None],
    [Lp, "NUMBER", None],
    [Lp, "STRING_DEFINITION", None],
    [Lp, "IF", [I, Lp]],
    [Lp, "ELSE", None],
    [Lp, "COMMENT", ["COMMENT", Lp]],
    [Lp, "STRING", [V, Lp]],
    [Lp, "CHAR", [V, Lp]],
    [Lp, "INT", [V, Lp]],
    [Lp, "FLOAT", [V, Lp]],
    [Lp, "PRINTF", [Pr, Lp]],
    [Lp, "SCANF", [Sc, Lp]],
    [Lp, "WHILE", [W, Lp]],
    [Lp, "RETURN", ["RETURN", Val, "INSTRUCTION_END"]],
]

R_table = [
    [R, "EOF", None],
    [R, "INCLUDE", None],
    [
        R,
        "LEFT_PARENTHESIS",
        ["LEFT_PARENTHESIS", A, "RIGHT_PARENTHESIS", "INSTRUCTION_END"],
    ],
    [R, "RIGHT_PARENTHESIS", None],
    [R, "LEFT_BLOCK", None],
    [R, "RIGHT_BLOCK", None],
    [R, "INSTRUCTION_END", None],
    [R, "COMMA", None],
    [R, "EQUAL", ["EQUAL", Val, "INSTRUCTION_END"]],
    [R, "LESS_THAN", None],
    [R, "GREATER_THAN", None],
    [R, "PLUS", None],
    [R, "MINUS", None],
    [R, "TIMES", None],
    [R, "DIVIDE", None],
    [R, "IDENTIFIER", None],
    [R, "CHAR_DEFINITION", None],
    [R, "NUMBER", None],
    [R, "STRING_DEFINITION", None],
    [R, "IF", None],
    [R, "ELSE", None],
    [R, "COMMENT", None],
    [R, "STRING", None],
    [R, "CHAR", None],
    [R, "INT", None],
    [R, "FLOAT", None],
    [R, "PRINTF", None],
    [R, "SCANF", None],
    [R, "WHILE", None],
    [R, "RETURN", None],
]

Sc_table = [
    [Sc, "EOF", None],
    [Sc, "INCLUDE", None],
    [Sc, "LEFT_PARENTHESIS", None],
    [Sc, "RIGHT_PARENTHESIS", None],
    [Sc, "LEFT_BLOCK", None],
    [Sc, "RIGHT_BLOCK", None],
    [Sc, "INSTRUCTION_END", None],
    [Sc, "COMMA", None],
    [Sc, "EQUAL", None],
    [Sc, "LESS_THAN", None],
    [Sc, "GREATER_THAN", None],
    [Sc, "PLUS", None],
    [Sc, "MINUS", None],
    [Sc, "TIMES", None],
    [Sc, "DIVIDE", None],
    [Sc, "IDENTIFIER", None],
    [Sc, "CHAR_DEFINITION", None],
    [Sc, "NUMBER", None],
    [Sc, "STRING_DEFINITION", None],
    [Sc, "IF", None],
    [Sc, "ELSE", None],
    [Sc, "COMMENT", None],
    [Sc, "STRING", None],
    [Sc, "CHAR", None],
    [Sc, "INT", None],
    [Sc, "FLOAT", None],
    [Sc, "PRINTF", None],
    [
        Sc,
        "SCANF",
        [
            "SCANF",
            "LEFT_PARENTHESIS",
            "STRING_DEFINITION",
            "COMMA",
            "AMPERSAND",
            "IDENTIFIER",
            "RIGHT_PARENTHESIS",
            "INSTRUCTION_END",
        ],
    ],
    [Sc, "WHILE", None],
    [Sc, "RETURN", None],
]

Pr_table = [
    [Pr, "EOF", None],
    [Pr, "INCLUDE", None],
    [Pr, "LEFT_PARENTHESIS", None],
    [Pr, "RIGHT_PARENTHESIS", None],
    [Pr, "LEFT_BLOCK", None],
    [Pr, "RIGHT_BLOCK", None],
    [Pr, "INSTRUCTION_END", None],
    [Pr, "COMMA", None],
    [Pr, "EQUAL", None],
    [Pr, "LESS_THAN", None],
    [Pr, "GREATER_THAN", None],
    [Pr, "PLUS", None],
    [Pr, "MINUS", None],
    [Pr, "TIMES", None],
    [Pr, "DIVIDE", None],
    [Pr, "IDENTIFIER", None],
    [Pr, "CHAR_DEFINITION", None],
    [Pr, "NUMBER", None],
    [Pr, "STRING_DEFINITION", None],
    [Pr, "IF", None],
    [Pr, "ELSE", None],
    [Pr, "COMMENT", None],
    [Pr, "STRING", None],
    [Pr, "CHAR", None],
    [Pr, "INT", None],
    [Pr, "FLOAT", None],
    [
        Pr,
        "PRINTF",
        [
            "PRINTF",
            "LEFT_PARENTHESIS",
            "STRING_DEFINITION",
            E,
            "RIGHT_PARENTHESIS",
            "INSTRUCTION_END",
        ],
    ],
    [Pr, "SCANF", None],
    [Pr, "WHILE", None],
    [Pr, "RETURN", None],
]

W_table = [
    [W, "EOF", None],
    [W, "INCLUDE", None],
    [W, "LEFT_PARENTHESIS", None],
    [W, "RIGHT_PARENTHESIS", None],
    [W, "LEFT_BLOCK", None],
    [W, "RIGHT_BLOCK", None],
    [W, "INSTRUCTION_END", None],
    [W, "COMMA", None],
    [W, "EQUAL", None],
    [W, "LESS_THAN", None],
    [W, "GREATER_THAN", None],
    [W, "PLUS", None],
    [W, "MINUS", None],
    [W, "TIMES", None],
    [W, "DIVIDE", None],
    [W, "IDENTIFIER", None],
    [W, "CHAR_DEFINITION", None],
    [W, "NUMBER", None],
    [W, "STRING_DEFINITION", None],
    [W, "IF", None],
    [W, "ELSE", None],
    [W, "COMMENT", None],
    [W, "STRING", None],
    [W, "CHAR", None],
    [W, "INT", None],
    [W, "FLOAT", None],
    [W, "PRINTF", None],
    [W, "SCANF", None],
    [
        W,
        "WHILE",
        [
            "WHILE",
            "LEFT_PARENTHESIS",
            C,
            "RIGHT_PARENTHESIS",
            "LEFT_BLOCK",
            L,
            "RIGHT_BLOCK",
            "INSTRUCTION_END",
        ],
    ],
    [W, "RETURN", None],
]

A_table = [
    [A, "EOF", None],
    [A, "INCLUDE", None],
    [A, "LEFT_PARENTHESIS", None],
    [A, "RIGHT_PARENTHESIS", ["VACIA"]],
    [A, "LEFT_BLOCK", None],
    [A, "RIGHT_BLOCK", None],
    [A, "INSTRUCTION_END", None],
    [A, "COMMA", None],
    [A, "EQUAL", None],
    [A, "LESS_THAN", None],
    [A, "GREATER_THAN", None],
    [A, "PLUS", None],
    [A, "MINUS", None],
    [A, "TIMES", None],
    [A, "DIVIDE", None],
    [A, "IDENTIFIER", [Val, E]],
    [A, "CHAR_DEFINITION", [Val, E]],
    [A, "NUMBER", [Val, E]],
    [A, "STRING_DEFINITION", [Val, E]],
    [A, "IF", None],
    [A, "ELSE", None],
    [A, "COMMENT", None],
    [A, "STRING", None],
    [A, "CHAR", None],
    [A, "INT", None],
    [A, "FLOAT", None],
    [A, "PRINTF", None],
    [A, "SCANF", None],
    [A, "WHILE", None],
    [A, "RETURN", None],
]

D_table = [
    [D, "EOF", None],
    [D, "INCLUDE", None],
    [D, "LEFT_PARENTHESIS", None],
    [D, "RIGHT_PARENTHESIS", None],
    [D, "LEFT_BLOCK", None],
    [D, "RIGHT_BLOCK", None],
    [D, "INSTRUCTION_END", None],
    [D, "COMMA", None],
    [D, "EQUAL", None],
    [D, "LESS_THAN", None],
    [D, "GREATER_THAN", None],
    [D, "PLUS", None],
    [D, "MINUS", None],
    [D, "TIMES", None],
    [D, "DIVIDE", None],
    [D, "IDENTIFIER", [Val, E]],
    [D, "CHAR_DEFINITION", [Val, E]],
    [D, "NUMBER", [Val, E]],
    [D, "STRING_DEFINITION", [Val, E]],
    [D, "IF", None],
    [D, "ELSE", None],
    [D, "COMMENT", None],
    [D, "STRING", None],
    [D, "CHAR", None],
    [D, "INT", None],
    [D, "FLOAT", None],
    [D, "PRINTF", None],
    [D, "SCANF", None],
    [D, "WHILE", None],
    [D, "RETURN", None],
]

E_table = [
    [E, "EOF", None],
    [E, "INCLUDE", None],
    [E, "LEFT_PARENTHESIS", None],
    [E, "RIGHT_PARENTHESIS", ["VACIA"]],
    [E, "LEFT_BLOCK", None],
    [E, "RIGHT_BLOCK", None],
    [E, "INSTRUCTION_END", None],
    [E, "COMMA", ["COMMA", D]],
    [E, "EQUAL", None],
    [E, "LESS_THAN", None],
    [E, "GREATER_THAN", None],
    [E, "PLUS", None],
    [E, "MINUS", None],
    [E, "TIMES", None],
    [E, "DIVIDE", None],
    [E, "IDENTIFIER", None],
    [E, "CHAR_DEFINITION", None],
    [E, "NUMBER", None],
    [E, "STRING_DEFINITION", None],
    [E, "IF", None],
    [E, "ELSE", None],
    [E, "COMMENT", None],
    [E, "STRING", None],
    [E, "CHAR", None],
    [E, "INT", None],
    [E, "FLOAT", None],
    [E, "PRINTF", None],
    [E, "SCANF", None],
    [E, "WHILE", None],
    [E, "RETURN", None],
]


general_table = (
    S_table
    + Sp_table
    + O_table
    + Op_table
    + T_table
    + Tp_table
    + Ov_table
    + V_table
    + Vp_table
    + N_table
    + Np_table
    + Val_table
    + Dt_table
    + I_table
    + Ip_table
    + M_table
    + C_table
    + Cp_table
    + B_Table
    + F_table
    + Fp_table
    + G_table
    + P_table
    + Pp_table
    + L_table
    + Lp_table
    + R_table
    + Sc_table
    + Pr_table
    + W_table
    + A_table
    + D_table
    + E_table
)


template = [
    [O, "EOF", None],
    [O, "INCLUDE", None],
    [O, "LEFT_PARENTHESIS", None],
    [O, "RIGHT_PARENTHESIS", None],
    [O, "LEFT_BLOCK", None],
    [O, "RIGHT_BLOCK", None],
    [O, "INSTRUCTION_END", None],
    [O, "COMMA", None],
    [O, "EQUAL", None],
    [O, "LESS_THAN", None],
    [O, "GREATER_THAN", None],
    [O, "PLUS", None],
    [O, "MINUS", None],
    [O, "TIMES", None],
    [O, "DIVIDE", None],
    [O, "IDENTIFIER", None],
    [O, "CHAR_DEFINITION", None],
    [O, "NUMBER", None],
    [O, "STRING_DEFINITION", None],
    [O, "IF", None],
    [O, "ELSE", None],
    [O, "COMMENT", None],
    [O, "STRING", None],
    [O, "CHAR", None],
    [O, "INT", None],
    [O, "FLOAT", None],
    [O, "PRINTF", None],
    [O, "SCANF", None],
    [O, "WHILE", None],
    [O, "RETURN", None],
]
